# Generated by Django 4.2.1 on 2023-06-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Sale', 'SALE'), ('Rent', 'RENT')], default='Sale', max_length=10),
        ),
    ]
