# Generated by Django 4.2.1 on 2023-06-07 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='floor',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.attachment'),
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='room_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='whatsapp',
            field=models.TextField(default=''),
        ),
    ]
