# Generated by Django 4.2.1 on 2023-06-07 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_currency_post_address_post_area_post_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authentication.currency'),
        ),
    ]
